if (!isServer) exitWith {};
_unit = _this select 0;

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
for '_i' from 1 to 8 do {_unit addItemToVest 'rhs_VOG25';};
for '_i' from 1 to 3 do {_unit addItemToVest 'rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer';};
for '_i' from 1 to 3 do {_unit addItemToVest 'rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red';};
_unit addBackpack 'B_Kitbag_rgr';
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_GRD40_Green';};
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_GRD40_Red';};
for '_i' from 1 to 6 do {_unit addItemToBackpack 'rhs_mag_M441_HE';};
for '_i' from 1 to 6 do {_unit addItemToBackpack 'rhs_mag_M433_HEDP';};
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_mag_m576';};
_unit addItemToBackpack 'rhs_mag_m661_green';
_unit addItemToBackpack 'rhs_mag_m662_red';
for '_i' from 1 to 2 do {_unit addItemToBackpack '1Rnd_SmokePurple_Grenade_shell';};
for '_i' from 1 to 2 do {_unit addItemToBackpack '1Rnd_SmokeGreen_Grenade_shell';};
for '_i' from 1 to 2 do {_unit addItemToBackpack '1Rnd_SmokeRed_Grenade_shell';};
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_mag_30Rnd_556x45_Mk318_Stanag';};
for '_i' from 1 to 4 do {_unit addItemToBackpack 'rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer';};
_unit addWeapon 'rhs_weap_m4_m203';
_unit addPrimaryWeaponItem 'rhsusf_acc_eotech_xps3';
