if (!isServer) exitWith {};
_unit = _this select 0;

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit addBackpack 'TRYK_B_Medbag_OD';
_unit linkItem 'ItemMap';
_unit linkItem 'ItemRadio';
_unit addItemToBackpack 'ACE_surgicalKit';
_unit addItemToBackpack 'ACE_personalAidKit';
for '_i' from 1 to 25 do {_unit addItemToBackpack 'ACE_fieldDressing';};
for '_i' from 1 to 15 do {_unit addItemToBackpack 'ACE_morphine';};
for '_i' from 1 to 15 do {_unit addItemToBackpack 'ACE_Epinephrine';};
for '_i' from 1 to 15 do {_unit addItemToBackpack 'ACE_packingBandage';};
for '_i' from 1 to 6 do {_unit addItemToBackpack 'ACE_salineIV';};
for '_i' from 1 to 6 do {_unit addItemToBackpack 'ACE_tourniquet';};
for '_i' from 1 to 15 do {_unit addItemToBackpack 'ACE_quikclot';};
