if (!isServer) exitWith {};
_unit = _this select 0;

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform 'usm_bdu_blk';
_unit addVest 'V_TacVestIR_blk';
_unit addItemToVest 'ACE_SpraypaintBlack';
_unit addItemToVest 'ACE_CableTie';
_unit addItemToVest 'ACE_Flashlight_KSF1';
for '_i' from 1 to 4 do {_unit addItemToVest 'rhs_30Rnd_545x39_AK';};
_unit addItemToVest 'rhs_30Rnd_545x39_AK_green';
for '_i' from 1 to 4 do {_unit addItemToVest 'rhs_mag_fakel';};
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_m7a3_cs';};
_unit addItemToVest 'rhs_mag_nspd';
_unit addItemToVest 'rhs_mag_rdg2_white';
_unit addHeadgear 'ZSH_1_ZV';
_unit addWeapon 'rhs_pzn_weap_ak74';
_unit addPrimaryWeaponItem 'rhs_acc_dtk';
_unit addPrimaryWeaponItem 'rhs_acc_2dpZenit';
_unit linkItem 'ItemCompass';
_unit linkItem 'ItemWatch';
_unit linkItem 'ItemRadio';
[_unit] call bn_equip_cdf_ace_med;
