if (!isServer) exitWith {};
_unit = _this select 0;

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;
_unit forceAddUniform 'LOP_U_CDF_Fatigue_01';
_unit addVest 'LOP_V_6B23_6Sh92_CDF';
_unit addItemToVest 'ACE_SpraypaintBlack';
_unit addItemToVest 'ACE_Flashlight_KSF1';
for '_i' from 1 to 4 do {_unit addItemToVest 'rhs_30Rnd_545x39_AK';};
_unit addItemToVest 'rhs_30Rnd_545x39_AK_green';
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_rgd5';};
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_nspd';};
for '_i' from 1 to 3 do {_unit addItemToVest 'RH_8Rnd_9x18_Mak';};
for '_i' from 1 to 2 do {_unit addItemToVest 'Chemlight_red';};
_unit addBackpack 'tf_rt1523g_black';
_unit addHeadgear 'LOP_H_Fieldcap_CDF';
_unit addWeapon 'rhs_pzn_weap_ak74';
_unit addPrimaryWeaponItem 'rhs_acc_dtk';
_unit addPrimaryWeaponItem 'rhs_acc_2dpZenit';
_unit addWeapon 'RH_mak';
_unit addWeapon 'Binocular';
_unit linkItem 'ItemCompass';
_unit linkItem 'ItemWatch';
_unit linkItem 'ItemRadio';
[_unit] call bn_equip_cdf_ace_med;
