_unit = _this select 0;
_unit forceAddUniform "rhs_uniform_vdv_mflora";
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_EarPlugs";
_unit addSecondaryWeaponItem "ACE_Flashlight_XL50";
_unit addVest "rhs_6b23_6sh92";
for '_i' from 1 to 4 do {_unit addItemToVest "rhs_30Rnd_545x39_7N22_AK";};
_unit addItemToVest "rhs_30Rnd_545x39_AK_green";
for '_i' from 1 to 2 do {_unit addItemToVest "rhs_mag_rgo";};
for '_i' from 1 to 2 do {_unit addItemToVest "rhs_mag_rdg2_white";};
_unit addBackpack "tf_bussole";
_unit addWeapon "rhs_weap_ak74m";
_unit addPrimaryWeaponItem "rhs_acc_dtk";
_unit addItemToUniform "ItemMap";
_unit linkItem "ItemCompass";
_unit addItemToUniform "tf_microdagr";
_unit linkItem "ItemRadio";
_unit linkItem "TRYK_TAC_boonie_SET_NV";
